import io.gitlab.arturbosch.detekt.Detekt
import org.gradle.jvm.tasks.Jar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.net.URI

plugins {
    `maven-publish`
    jacoco // for test coverage reports

    kotlin("jvm") version Versions.kotlin

    id("io.gitlab.arturbosch.detekt") version Versions.detekt
}

group = "ai.blindspot"
version = "0.0.1-SNAPSHOT"

repositories {
    jcenter()
}

detekt {
    parallel = true
    input = files(subprojects.map { it.projectDir }, "buildSrc")
    config = files(rootDir.resolve("detekt-config.yml"))
}

dependencies {
    implementation(Libs.kotlinStdlib) // kotlin std
    implementation(Libs.kotlinLogging) // logging DSL

    // testing
    testImplementation(TestLibs.kotlinTest) // kotlin idiomatic testing
    testImplementation(TestLibs.kotlinTestJunit5) // kotlin.test wrapper for Junit5
    testImplementation(TestLibs.mockk) // mock framework
    testImplementation(TestLibs.logbackClassic) // logging framework for the tests
    testImplementation(TestLibs.junitApi) // junit testing framework
    testImplementation(TestLibs.junitParams) // generated parameters for tests

    testRuntime(TestLibs.junitEngine) // testing runtime
}

/**
 * Folder with stored jacoco test coverage results
 */
val jacocoReportDir = "$buildDir${File.separator}jacoco${File.separator}reports.xml"

tasks {
    test {
        @Suppress("UnstableApiUsage") // Required for running tests, however the api is still incubating
        useJUnitPlatform()
    }

    check {
        dependsOn(detekt, jacocoTestCoverageVerification) // fails when the code coverage is below value specified in Props.codeCoverageMinimum
    }

    jacocoTestReport {
        dependsOn(test)

        @Suppress("UnstableApiUsage") // Required for test coverage reports, however the api is still incubating
        reports {
            csv.isEnabled = false
            xml.isEnabled = true
            xml.destination = file(jacocoReportDir)
        }

        classDirectories.setFrom(
            sourceSets.main.get().output.asFileTree.matching {
                exclude(IgnoredFiles.jacoco)
            }
        )
    }

    jacocoTestCoverageVerification {
        dependsOn(jacocoTestReport)

        violationRules {
            rule { limit { minimum = Props.codeCoverageMinimum.getOrDefault("0.9").toBigDecimal() } }
        }

        classDirectories.setFrom(
            sourceSets.main.get().output.asFileTree.matching {
                exclude(IgnoredFiles.jacoco)
            }
        )
    }

    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = "1.8"
    }

    withType<Detekt> {
        exclude(IgnoredFiles.detekt) // exclude autogenerated packages
    }
}

val sourcesJar by tasks.creating(Jar::class) {
    classifier = "sources"
    from(sourceSets.main.get().allSource)
}

val javadocJar by tasks.creating(Jar::class) {
    classifier = "javadoc"
    from(tasks.javadoc)
}

publishing {
    publications {
        create<MavenPublication>("default") {
            from(components["java"])
            artifact(sourcesJar)
            artifact(javadocJar)
        }
    }
    repositories {
        maven {
            val releasesRepoUrl = URI(Props.nexusUrlReleases.get())
            val snapshotsRepoUrl = URI(Props.nexusUrlSnapshots.get())

            url = if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl

            credentials {
                username = Props.nexusUser.get()
                password = Props.nexusPassword.get()
            }
        }
    }
}
